"""
# Using fishaudio/openaudio-s1-mini from Hugging Face

This notebook demonstrates how to use the `fishaudio/openaudio-s1-mini` model from Hugging Face for audio processing tasks.
We will cover:
- Installing necessary libraries
- Loading the model and processor
- Preparing an audio input
- Performing inference
- Handling the output
"""

# Code cell for pip installs
!pip install transformers
!pip install torch
!pip install torchaudio
!pip install librosa
!pip install huggingface_hub

import torch
from transformers import AutoModelForSpeechSeq2Seq, AutoProcessor, AutoModelForTextToWaveform
import torchaudio
import librosa
from huggingface_hub import login
import IPython.display as ipd

"""
## Hugging Face Authentication

To download and use this model, you need to be authenticated with Hugging Face.
1. If you don't have one, create a Hugging Face account and get an access token (User Access Tokens).
2. Replace `"YOUR_HUGGING_FACE_TOKEN"` in the code cell below with your actual token.
"""

# Code cell for Hugging Face login
from huggingface_hub import login # Already imported above, but common to see it here too. Kept for clarity as per user prompt structure.

# Replace with your Hugging Face User Access Token
# It's recommended to use Colab's secrets manager for better security:
# from google.colab import userdata
# hf_token = userdata.get('HF_TOKEN')
# login(token=hf_token)

hf_token = "YOUR_HUGGING_FACE_TOKEN" # << REPLACE THIS !!
if hf_token == "YOUR_HUGGING_FACE_TOKEN" or hf_token == "":
    print("Please replace 'YOUR_HUGGING_FACE_TOKEN' with your actual Hugging Face token.")
else:
    login(token=hf_token)
    print("Successfully logged in to Hugging Face Hub.")

# Load the processor and model
processor = AutoProcessor.from_pretrained("fishaudio/openaudio-s1-mini")
model = AutoModelForTextToWaveform.from_pretrained("fishaudio/openaudio-s1-mini")

"""
## Text Input for TTS

Enter the text you want the model to convert to speech in the field below.
"""

#@title Enter Text for Speech Synthesis
text_input = "Hello, this is a test audio generated by openaudio-s1-mini using a Colab form." #@param {type:"string"}

print(f"Text to synthesize: {text_input}")
inputs = processor(text=text_input, return_tensors="pt")

# Perform inference
with torch.no_grad():
    audio_waveform = model.generate(**inputs)

"""
## Audio Output

The generated audio will be played back below.
"""

# Code cell for audio playback
# import IPython.display as ipd # Already imported at the top
# import torchaudio # Already imported at the top

# Assuming 'audio_waveform' is the output from model.generate(**inputs)
# and 'model' is the loaded Hugging Face model

# Squeeze the waveform if it has an extra batch dimension (e.g., [1, T]) to [T]
if audio_waveform.ndim > 1 and audio_waveform.shape[0] == 1:
    audio_waveform_squeezed = audio_waveform.squeeze(0)
else:
    audio_waveform_squeezed = audio_waveform

# Ensure the waveform is on CPU for IPython.display.Audio
audio_waveform_cpu = audio_waveform_squeezed.cpu()

# Get the sampling rate from the model's configuration
# For many TTS models, this is available in model.config.sampling_rate
# or sometimes processor.feature_extractor.sampling_rate
sampling_rate = model.config.sampling_rate
# If model.config.sampling_rate is not available, try a common default or processor's rate
# if not hasattr(model.config, 'sampling_rate'):
#     # Fallback: Check processor or use a common default like 16000 or 24000
#     if hasattr(processor, 'feature_extractor') and hasattr(processor.feature_extractor, 'sampling_rate'):
#         sampling_rate = processor.feature_extractor.sampling_rate
#     else:
#         sampling_rate = 24000 # A common TTS sampling rate, adjust if known for the model
#     print(f"Warning: model.config.sampling_rate not found. Using sampling rate: {sampling_rate}")

print(f"Playing audio at {sampling_rate} Hz.")
display(ipd.Audio(audio_waveform_cpu, rate=sampling_rate))

# Option to save the audio
# output_filename = "generated_speech.wav"
# torchaudio.save(output_filename, audio_waveform_cpu.unsqueeze(0), sampling_rate) # unsqueeze to add channel dim if needed by save
# print(f"Audio also saved as {output_filename}")
